notify-update: true
replant:
  # check link below for sounds
  # "https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html"
  sound: ITEM_SHOVEL_FLATTEN
  # 'none' to disable checking tool has required enchantment, below for a list of enchantments
  # "https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html"
  # if you use custom enchantments they work as well
  enchantment: none
  # which world is enabled for replant events
  worlds:
    - world
    - world_nether
    - world_the_end
    - test
blocks:
  MELON:
    enable: false
    damage: 1
    drops:
      melon:
        type: MELON
        amount:
          min: 3
          max: 7
    experience:
      enable: true
      chance: 0.30
      amount: 1
      particle:
        enable: true
        type: TOTEM
        offsetX: 0.3
        offsetY: 0.3
        offsetZ: 0.3
        count: 25
      sound:
        enable: true
        type: BLOCK_AMETHYST_BLOCK_BREAK
        volume: 0.75
        pitch: 1.0
  PUMPKIN:
    enable: false
    damage: 1
    drops:
      pumpkin:
        type: PUMPKIN
        amount:
          min: 1
          max: 1
    experience:
      enable: true
      chance: 0.30
      amount: 1
      particle:
        enable: true
        type: TOTEM
        offsetX: 0.3
        offsetY: 0.3
        offsetZ: 0.3
        count: 25
      sound:
        enable: true
        type: BLOCK_AMETHYST_BLOCK_BREAK
        volume: 0.75
        pitch: 1.0
  CARROTS:
    enable: true
    max-age: 7
    damage: 1
    drops:
      carrot:
        type: CARROT
        amount:
          min: 2
          max: 5
    experience:
      enable: true
      chance: 0.30
      amount: 1
      particle:
        enable: true
        type: TOTEM
        offsetX: 0.3
        offsetY: 0.3
        offsetZ: 0.3
        count: 25
      sound:
        enable: true
        type: BLOCK_AMETHYST_BLOCK_BREAK
        volume: 0.75
        pitch: 1.0
  POTATOES:
    enable: true
    max-age: 7
    damage: 1
    drops:
      potato:
        type: POTATO
        amount:
          min: 2
          max: 5
    experience:
      enable: true
      chance: 0.30
      amount: 1
      particle:
        enable: true
        type: TOTEM
        offsetX: 0.3
        offsetY: 0.3
        offsetZ: 0.3
        count: 25
      sound:
        enable: true
        type: BLOCK_AMETHYST_BLOCK_BREAK
        volume: 0.75
        pitch: 1.0
  WHEAT:
    enable: true
    max-age: 7
    damage: 1
    drops:
      wheat:
        type: WHEAT
        amount:
          min: 1
          max: 1
      wheat_seeds:
        type: WHEAT_SEEDS
        amount:
          min: 1
          max: 3
    experience:
      enable: true
      chance: 0.30
      amount: 1
      particle:
        enable: true
        type: TOTEM
        offsetX: 0.3
        offsetY: 0.3
        offsetZ: 0.3
        count: 25
      sound:
        enable: true
        type: BLOCK_AMETHYST_BLOCK_BREAK
        volume: 0.75
        pitch: 1.0
  BEETROOTS:
    enable: true
    max-age: 3
    damage: 1
    drops:
      beetroot:
        type: BEETROOT
        amount:
          min: 1
          max: 1
      beetroot_seeds:
        type: BEETROOT_SEEDS
        amount:
          min: 1
          max: 3
    experience:
      enable: true
      chance: 0.30
      amount: 1
      particle:
        enable: true
        type: TOTEM
        offsetX: 0.3
        offsetY: 0.3
        offsetZ: 0.3
        count: 25
      sound:
        enable: true
        type: BLOCK_AMETHYST_BLOCK_BREAK
        volume: 0.75
        pitch: 1.0
  COCOA:
    enable: true
    max-age: 2
    damage: 1
    drops:
      cocoa_beans:
        type: COCOA_BEANS
        amount:
          min: 1
          max: 2
    experience:
      enable: true
      chance: 0.30
      amount: 1
      particle:
        enable: true
        type: TOTEM
        offsetX: 0.3
        offsetY: 0.3
        offsetZ: 0.3
        count: 25
      sound:
        enable: true
        type: BLOCK_AMETHYST_BLOCK_BREAK
        volume: 0.75
        pitch: 1.0
  NETHER_WART:
    enable: true
    max-age: 3
    damage: 1
    drops:
      nether_wart:
        type: NETHER_WART
        amount:
          min: 1
          max: 3
    experience:
      enable: true
      chance: 0.30
      amount: 1
      particle:
        enable: true
        type: TOTEM
        offsetX: 0.3
        offsetY: 0.3
        offsetZ: 0.3
        count: 25
      sound:
        enable: true
        type: BLOCK_AMETHYST_BLOCK_BREAK
        volume: 0.75
        pitch: 1.0
